### ISSUE TITLE
[BUG] Check if half_scan_percentage alters the chosen acceleration factors / Add option for 1D masks

### ISSUE THREAD

**Issue by wdika** [wdika/mridc#10]
**Describe the bug**
[`half_scan_percentage`](https://github.com/wdika/mridc/blob/670b4c56e74d27195e9b1dc8834b1dc5420abebd/mridc/data/subsample.py#L64) works only with `2D` masks. 

**To Reproduce**
Duplicate a test function for `1D` masking like [this](https://github.com/wdika/mridc/blob/670b4c56e74d27195e9b1dc8834b1dc5420abebd/tests/test_subsample.py#L20) and add `half_scan_percentage > 0`.

**Expected behavior**
It should be working on both `1D` and `2D` masks. Add this option for `1D` masking as well.

**Environment**
Operating System: `ubuntu-latest` Python Version: `>= 3.9` PyTorch Version: `>= 1.9`

**Comment by jerke123** [comment]
Additionally, account for the half_scan_percentage in the rest of the mask that remains, as to maintain the desired acceleration factor

**Comment by wdika** [comment]
> Additionally, account for the half_scan_percentage in the rest of the mask that remains, as to maintain the desired acceleration factor

Good catch!

Check for example [here ](https://github.com/wdika/mridc/blob/eeea9e08b3de4df37c027c5355a3689825895e23/mridc/data/subsample.py#L361) if the acceleration factor is altered after applying the half scan. If yes, the half scan needs to be applied before. For example, change the shape of the mask to be created and pad it with zeros after.

**Comment by wdika** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backlog](https://trello.com/c/B6oaQXbp/1-backlog)

**Comment by wdika** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] Check if half_scan_percentage alters the chosen acceleration factors / Add option for 1D masks #10](https://trello.com/c/QwSOhFz9/1-bug-check-if-halfscanpercentage-alters-the-chosen-acceleration-factors-add-option-for-1d-masks-10)
